In [1]:
import numpy as np
import pandas as pd 

In [2]:
x=[1,2,3,5,1,2]
nx=np.array(x)

In [3]:
print(nx)

[1 2 3 5 1 2]


In [4]:
print(nx.shape)

(6,)


In [5]:
ny=np.array([[1,2,3],[4,5,6]])

In [6]:
print(ny.shape)

(2, 3)


In [7]:
ny

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
one=np.arange(1,100,.2)
one

array([ 1. ,  1.2,  1.4,  1.6,  1.8,  2. ,  2.2,  2.4,  2.6,  2.8,  3. ,
        3.2,  3.4,  3.6,  3.8,  4. ,  4.2,  4.4,  4.6,  4.8,  5. ,  5.2,
        5.4,  5.6,  5.8,  6. ,  6.2,  6.4,  6.6,  6.8,  7. ,  7.2,  7.4,
        7.6,  7.8,  8. ,  8.2,  8.4,  8.6,  8.8,  9. ,  9.2,  9.4,  9.6,
        9.8, 10. , 10.2, 10.4, 10.6, 10.8, 11. , 11.2, 11.4, 11.6, 11.8,
       12. , 12.2, 12.4, 12.6, 12.8, 13. , 13.2, 13.4, 13.6, 13.8, 14. ,
       14.2, 14.4, 14.6, 14.8, 15. , 15.2, 15.4, 15.6, 15.8, 16. , 16.2,
       16.4, 16.6, 16.8, 17. , 17.2, 17.4, 17.6, 17.8, 18. , 18.2, 18.4,
       18.6, 18.8, 19. , 19.2, 19.4, 19.6, 19.8, 20. , 20.2, 20.4, 20.6,
       20.8, 21. , 21.2, 21.4, 21.6, 21.8, 22. , 22.2, 22.4, 22.6, 22.8,
       23. , 23.2, 23.4, 23.6, 23.8, 24. , 24.2, 24.4, 24.6, 24.8, 25. ,
       25.2, 25.4, 25.6, 25.8, 26. , 26.2, 26.4, 26.6, 26.8, 27. , 27.2,
       27.4, 27.6, 27.8, 28. , 28.2, 28.4, 28.6, 28.8, 29. , 29.2, 29.4,
       29.6, 29.8, 30. , 30.2, 30.4, 30.6, 30.8, 31

In [9]:
print(one.size)

495


In [10]:
two=np.linspace(1,100,200)
two

array([  1.        ,   1.49748744,   1.99497487,   2.49246231,
         2.98994975,   3.48743719,   3.98492462,   4.48241206,
         4.9798995 ,   5.47738693,   5.97487437,   6.47236181,
         6.96984925,   7.46733668,   7.96482412,   8.46231156,
         8.95979899,   9.45728643,   9.95477387,  10.45226131,
        10.94974874,  11.44723618,  11.94472362,  12.44221106,
        12.93969849,  13.43718593,  13.93467337,  14.4321608 ,
        14.92964824,  15.42713568,  15.92462312,  16.42211055,
        16.91959799,  17.41708543,  17.91457286,  18.4120603 ,
        18.90954774,  19.40703518,  19.90452261,  20.40201005,
        20.89949749,  21.39698492,  21.89447236,  22.3919598 ,
        22.88944724,  23.38693467,  23.88442211,  24.38190955,
        24.87939698,  25.37688442,  25.87437186,  26.3718593 ,
        26.86934673,  27.36683417,  27.86432161,  28.36180905,
        28.85929648,  29.35678392,  29.85427136,  30.35175879,
        30.84924623,  31.34673367,  31.84422111,  32.34

In [11]:
n3=np.random.rand(100)
n3

array([0.32453729, 0.50746213, 0.92819873, 0.62556742, 0.07136243,
       0.16496298, 0.90108765, 0.50729683, 0.28194824, 0.34326154,
       0.09567413, 0.01346955, 0.88279638, 0.87580521, 0.31484564,
       0.29449896, 0.59939479, 0.74552167, 0.57393422, 0.0546072 ,
       0.06491624, 0.35198229, 0.93403497, 0.14818746, 0.55645316,
       0.17964286, 0.75316422, 0.09938432, 0.05095001, 0.91474608,
       0.8831458 , 0.92653881, 0.09248922, 0.07282434, 0.50092757,
       0.89081545, 0.45291643, 0.07715429, 0.58601995, 0.60575234,
       0.51742438, 0.59713799, 0.75465543, 0.77643657, 0.42892449,
       0.72317623, 0.80202746, 0.54201668, 0.74052994, 0.85708275,
       0.69513115, 0.38674939, 0.74996151, 0.04598044, 0.53188508,
       0.83300532, 0.1587677 , 0.05864968, 0.08293104, 0.41383427,
       0.7400934 , 0.29216095, 0.15302708, 0.50017718, 0.97015502,
       0.2557147 , 0.4597411 , 0.62390324, 0.49257212, 0.03255367,
       0.94779366, 0.28705026, 0.01907255, 0.30923971, 0.58528

In [12]:
n4=np.random.randint(1,10,100)
n4

array([1, 1, 2, 3, 7, 9, 2, 5, 6, 4, 5, 5, 6, 3, 8, 8, 4, 1, 9, 4, 3, 1,
       5, 6, 9, 6, 5, 3, 6, 9, 4, 9, 1, 8, 3, 6, 5, 2, 6, 5, 7, 9, 9, 7,
       4, 4, 7, 4, 6, 5, 3, 1, 9, 4, 4, 7, 1, 6, 6, 3, 8, 7, 7, 5, 3, 9,
       3, 6, 8, 6, 8, 7, 6, 8, 7, 8, 4, 3, 4, 5, 9, 3, 8, 9, 7, 5, 1, 8,
       7, 3, 4, 7, 5, 3, 1, 1, 8, 4, 2, 4])

In [13]:
n4.reshape((10,10))

array([[1, 1, 2, 3, 7, 9, 2, 5, 6, 4],
       [5, 5, 6, 3, 8, 8, 4, 1, 9, 4],
       [3, 1, 5, 6, 9, 6, 5, 3, 6, 9],
       [4, 9, 1, 8, 3, 6, 5, 2, 6, 5],
       [7, 9, 9, 7, 4, 4, 7, 4, 6, 5],
       [3, 1, 9, 4, 4, 7, 1, 6, 6, 3],
       [8, 7, 7, 5, 3, 9, 3, 6, 8, 6],
       [8, 7, 6, 8, 7, 8, 4, 3, 4, 5],
       [9, 3, 8, 9, 7, 5, 1, 8, 7, 3],
       [4, 7, 5, 3, 1, 1, 8, 4, 2, 4]])

In [14]:
n4.reshape((10,5,2))

array([[[1, 1],
        [2, 3],
        [7, 9],
        [2, 5],
        [6, 4]],

       [[5, 5],
        [6, 3],
        [8, 8],
        [4, 1],
        [9, 4]],

       [[3, 1],
        [5, 6],
        [9, 6],
        [5, 3],
        [6, 9]],

       [[4, 9],
        [1, 8],
        [3, 6],
        [5, 2],
        [6, 5]],

       [[7, 9],
        [9, 7],
        [4, 4],
        [7, 4],
        [6, 5]],

       [[3, 1],
        [9, 4],
        [4, 7],
        [1, 6],
        [6, 3]],

       [[8, 7],
        [7, 5],
        [3, 9],
        [3, 6],
        [8, 6]],

       [[8, 7],
        [6, 8],
        [7, 8],
        [4, 3],
        [4, 5]],

       [[9, 3],
        [8, 9],
        [7, 5],
        [1, 8],
        [7, 3]],

       [[4, 7],
        [5, 3],
        [1, 1],
        [8, 4],
        [2, 4]]])

In [15]:
n1=np.random.randint(1,10,(5,5))
n2=np.random.randint(1,10,(5,5))

In [16]:
n1+n2

array([[10,  8, 12, 12, 13],
       [ 3, 10,  3, 14, 10],
       [ 9, 14,  4, 11, 17],
       [ 5, 12,  8,  8,  8],
       [16,  5,  9, 11, 16]])

In [17]:
n1*n2

array([[16, 15, 35, 35, 36],
       [ 2, 25,  2, 45,  9],
       [14, 48,  3, 18, 72],
       [ 4, 32, 12, 12, 12],
       [63,  4, 20, 24, 63]])

In [18]:
n1+10

array([[18, 13, 15, 17, 14],
       [12, 15, 12, 15, 11],
       [12, 18, 13, 12, 19],
       [14, 18, 16, 16, 12],
       [19, 11, 15, 13, 19]])

In [19]:
n1.dot(n2)

array([[ 89, 129,  94, 158, 209],
       [ 35,  71,  35,  91, 116],
       [ 98, 112,  65, 185, 189],
       [ 78, 128,  62, 174, 206],
       [120, 128, 111, 177, 211]])

In [20]:
n1,n2

(array([[8, 3, 5, 7, 4],
        [2, 5, 2, 5, 1],
        [2, 8, 3, 2, 9],
        [4, 8, 6, 6, 2],
        [9, 1, 5, 3, 9]]),
 array([[2, 5, 7, 5, 9],
        [1, 5, 1, 9, 9],
        [7, 6, 1, 9, 8],
        [1, 4, 2, 2, 6],
        [7, 4, 4, 8, 7]]))

In [21]:
n1-n2

array([[ 6, -2, -2,  2, -5],
       [ 1,  0,  1, -4, -8],
       [-5,  2,  2, -7,  1],
       [ 3,  4,  4,  4, -4],
       [ 2, -3,  1, -5,  2]])

In [22]:
n6=np.random.randint(1,10,10)

In [23]:
n6

array([4, 2, 6, 7, 4, 5, 6, 2, 2, 2])

In [24]:
n7=np.random.randint(1,10,(4,4))
n7

array([[5, 9, 9, 2],
       [3, 1, 5, 8],
       [1, 9, 6, 4],
       [7, 5, 4, 2]])

In [25]:
print(n7[0])

[5 9 9 2]


In [26]:
print(n7[:,0])

[5 3 1 7]


In [27]:
print(n7[-1])

[7 5 4 2]


In [28]:
print(n7[:2,2:])

[[9 2]
 [5 8]]


In [29]:
n7.flatten() #makes 1 dimension

array([5, 9, 9, 2, 3, 1, 5, 8, 1, 9, 6, 4, 7, 5, 4, 2])

In [31]:
x=n7

In [32]:
x.transpose()#row to coloum, coloum to row

array([[5, 3, 1, 7],
       [9, 1, 9, 5],
       [9, 5, 6, 4],
       [2, 8, 4, 2]])

In [33]:
n7.max()

9

In [34]:
n7.mean()

5.0

In [35]:
n7.sum()

80

In [36]:
n7.sum(axis=0)

array([16, 24, 24, 16])

In [37]:
n7.sum(axis=1)

array([25, 17, 20, 18])

In [38]:
n7.argmax() #gives index no.

1

In [39]:
a=np.random.randint(1,100,(3,2))
b=np.random.randint(1,100,(3,2))
c=np.random.randint(1,100,(2,3))

print(a)
print(b)
print(c)

[[92 72]
 [34 65]
 [14 64]]
[[55 77]
 [98 73]
 [75 25]]
[[78 82 49]
 [95  3 34]]


In [41]:
np.vstack((a,b))

array([[92, 72],
       [34, 65],
       [14, 64],
       [55, 77],
       [98, 73],
       [75, 25]])

In [42]:
np.hstack((a,b))

array([[92, 72, 55, 77],
       [34, 65, 98, 73],
       [14, 64, 75, 25]])

In [ ]:
np.vstack((a,c,T))

In [45]:
m=np.array([1,2,3,4,2,2,4,4,3,3,5,6,1,2,3,4,5,6,7,8,9,])

In [46]:
#boolean filter
m>5

array([False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False, False,  True,
        True,  True,  True])

In [47]:
m[m>5]

array([6, 6, 7, 8, 9])

In [48]:
m[m==2]

array([2, 2, 2, 2])

In [49]:
m[m!=2]

array([1, 3, 4, 4, 4, 3, 3, 5, 6, 1, 3, 4, 5, 6, 7, 8, 9])

In [52]:
m[(m>2)&(m<8)]

array([3, 4, 4, 4, 3, 3, 5, 6, 3, 4, 5, 6, 7])