In [4]:
import numpy as np
import pandas as pd 

In [6]:
x=[1,2,3,5,1,2]
nx=np.array(x)

In [7]:
print(nx)

[1 2 3 5 1 2]


In [8]:
print(nx.shape)

(6,)


In [9]:
ny=np.array([[1,2,3],[4,5,6]])

In [10]:
print(ny.shape)

(2, 3)


In [11]:
ny

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
one=np.arange(1,100,.2)
one

array([ 1. ,  1.2,  1.4,  1.6,  1.8,  2. ,  2.2,  2.4,  2.6,  2.8,  3. ,
        3.2,  3.4,  3.6,  3.8,  4. ,  4.2,  4.4,  4.6,  4.8,  5. ,  5.2,
        5.4,  5.6,  5.8,  6. ,  6.2,  6.4,  6.6,  6.8,  7. ,  7.2,  7.4,
        7.6,  7.8,  8. ,  8.2,  8.4,  8.6,  8.8,  9. ,  9.2,  9.4,  9.6,
        9.8, 10. , 10.2, 10.4, 10.6, 10.8, 11. , 11.2, 11.4, 11.6, 11.8,
       12. , 12.2, 12.4, 12.6, 12.8, 13. , 13.2, 13.4, 13.6, 13.8, 14. ,
       14.2, 14.4, 14.6, 14.8, 15. , 15.2, 15.4, 15.6, 15.8, 16. , 16.2,
       16.4, 16.6, 16.8, 17. , 17.2, 17.4, 17.6, 17.8, 18. , 18.2, 18.4,
       18.6, 18.8, 19. , 19.2, 19.4, 19.6, 19.8, 20. , 20.2, 20.4, 20.6,
       20.8, 21. , 21.2, 21.4, 21.6, 21.8, 22. , 22.2, 22.4, 22.6, 22.8,
       23. , 23.2, 23.4, 23.6, 23.8, 24. , 24.2, 24.4, 24.6, 24.8, 25. ,
       25.2, 25.4, 25.6, 25.8, 26. , 26.2, 26.4, 26.6, 26.8, 27. , 27.2,
       27.4, 27.6, 27.8, 28. , 28.2, 28.4, 28.6, 28.8, 29. , 29.2, 29.4,
       29.6, 29.8, 30. , 30.2, 30.4, 30.6, 30.8, 31

In [13]:
print(one.size)

495


In [15]:
two=np.linspace(1,100,200)
two

array([  1.        ,   1.49748744,   1.99497487,   2.49246231,
         2.98994975,   3.48743719,   3.98492462,   4.48241206,
         4.9798995 ,   5.47738693,   5.97487437,   6.47236181,
         6.96984925,   7.46733668,   7.96482412,   8.46231156,
         8.95979899,   9.45728643,   9.95477387,  10.45226131,
        10.94974874,  11.44723618,  11.94472362,  12.44221106,
        12.93969849,  13.43718593,  13.93467337,  14.4321608 ,
        14.92964824,  15.42713568,  15.92462312,  16.42211055,
        16.91959799,  17.41708543,  17.91457286,  18.4120603 ,
        18.90954774,  19.40703518,  19.90452261,  20.40201005,
        20.89949749,  21.39698492,  21.89447236,  22.3919598 ,
        22.88944724,  23.38693467,  23.88442211,  24.38190955,
        24.87939698,  25.37688442,  25.87437186,  26.3718593 ,
        26.86934673,  27.36683417,  27.86432161,  28.36180905,
        28.85929648,  29.35678392,  29.85427136,  30.35175879,
        30.84924623,  31.34673367,  31.84422111,  32.34

In [16]:
n3=np.random.rand(100)
n3

array([2.29001496e-01, 1.66332828e-01, 3.19119406e-01, 9.73232472e-01,
       1.14603119e-01, 8.31407927e-01, 2.61251871e-01, 2.96805460e-01,
       6.87131332e-02, 4.31934138e-02, 8.33998493e-01, 9.70098874e-01,
       5.21262437e-01, 7.87568108e-02, 1.21064807e-01, 2.49884585e-01,
       8.52756395e-01, 5.69216145e-01, 2.04564782e-01, 3.99455731e-01,
       5.96295451e-01, 8.99367702e-01, 3.99855381e-01, 2.38685447e-01,
       4.83109542e-01, 4.25545480e-02, 1.31519041e-01, 7.66023217e-02,
       6.01375878e-01, 2.26989420e-01, 6.64294878e-01, 7.54723382e-02,
       6.59435898e-01, 5.42770585e-01, 3.48701681e-01, 1.98561563e-01,
       5.72518708e-01, 7.55631403e-01, 3.13007011e-01, 2.83317446e-01,
       5.80906644e-01, 7.78978686e-02, 8.12493169e-01, 9.29538629e-01,
       4.67267355e-01, 7.57136912e-01, 4.22526550e-01, 4.63833409e-01,
       5.66960140e-01, 5.38642227e-01, 9.76141422e-01, 3.28882405e-01,
       1.87950390e-01, 9.44447890e-01, 5.42681946e-04, 8.08113245e-01,
      

In [17]:
n4=np.random.randint(1,10,100)
n4

array([9, 9, 2, 2, 6, 2, 3, 2, 1, 9, 4, 5, 6, 7, 9, 8, 7, 9, 4, 1, 9, 3,
       2, 7, 5, 6, 6, 7, 9, 7, 1, 5, 8, 3, 4, 9, 8, 5, 6, 1, 8, 2, 1, 5,
       1, 6, 5, 4, 1, 6, 3, 9, 4, 5, 4, 4, 3, 2, 8, 1, 2, 1, 7, 1, 1, 2,
       6, 7, 5, 9, 2, 2, 2, 1, 3, 7, 6, 4, 6, 3, 9, 6, 2, 8, 5, 1, 6, 2,
       9, 1, 5, 5, 2, 1, 2, 4, 1, 6, 3, 5])

In [18]:
n4.reshape((10,10))

array([[9, 9, 2, 2, 6, 2, 3, 2, 1, 9],
       [4, 5, 6, 7, 9, 8, 7, 9, 4, 1],
       [9, 3, 2, 7, 5, 6, 6, 7, 9, 7],
       [1, 5, 8, 3, 4, 9, 8, 5, 6, 1],
       [8, 2, 1, 5, 1, 6, 5, 4, 1, 6],
       [3, 9, 4, 5, 4, 4, 3, 2, 8, 1],
       [2, 1, 7, 1, 1, 2, 6, 7, 5, 9],
       [2, 2, 2, 1, 3, 7, 6, 4, 6, 3],
       [9, 6, 2, 8, 5, 1, 6, 2, 9, 1],
       [5, 5, 2, 1, 2, 4, 1, 6, 3, 5]])

In [19]:
n4.reshape((10,5,2))

array([[[9, 9],
        [2, 2],
        [6, 2],
        [3, 2],
        [1, 9]],

       [[4, 5],
        [6, 7],
        [9, 8],
        [7, 9],
        [4, 1]],

       [[9, 3],
        [2, 7],
        [5, 6],
        [6, 7],
        [9, 7]],

       [[1, 5],
        [8, 3],
        [4, 9],
        [8, 5],
        [6, 1]],

       [[8, 2],
        [1, 5],
        [1, 6],
        [5, 4],
        [1, 6]],

       [[3, 9],
        [4, 5],
        [4, 4],
        [3, 2],
        [8, 1]],

       [[2, 1],
        [7, 1],
        [1, 2],
        [6, 7],
        [5, 9]],

       [[2, 2],
        [2, 1],
        [3, 7],
        [6, 4],
        [6, 3]],

       [[9, 6],
        [2, 8],
        [5, 1],
        [6, 2],
        [9, 1]],

       [[5, 5],
        [2, 1],
        [2, 4],
        [1, 6],
        [3, 5]]])

In [20]:
n1=np.random.randint(1,10,(5,5))
n2=np.random.randint(1,10,(5,5))

In [21]:
n1+n2

array([[ 8,  9,  8,  9,  7],
       [ 8, 15,  8, 11, 13],
       [ 9, 12,  6, 15,  2],
       [11,  7,  5, 14, 10],
       [11,  2, 13, 15, 17]])

In [22]:
n1*n2

array([[ 7, 14,  7, 18, 12],
       [12, 54, 12, 30, 36],
       [18, 27,  8, 56,  1],
       [28, 10,  4, 45,  9],
       [24,  1, 40, 54, 72]])

In [23]:
n1+10

array([[11, 12, 11, 13, 14],
       [16, 19, 16, 15, 19],
       [16, 13, 14, 18, 11],
       [14, 15, 11, 19, 11],
       [13, 11, 15, 19, 19]])

In [24]:
n1.dot(n2)

array([[ 67,  38,  57,  64,  71],
       [185, 169, 164, 211, 177],
       [124, 113,  96, 128, 114],
       [112,  86,  84, 112, 122],
       [173,  99, 141, 158, 171]])

In [25]:
n1,n2

(array([[1, 2, 1, 3, 4],
        [6, 9, 6, 5, 9],
        [6, 3, 4, 8, 1],
        [4, 5, 1, 9, 1],
        [3, 1, 5, 9, 9]]),
 array([[7, 7, 7, 6, 3],
        [2, 6, 2, 6, 4],
        [3, 9, 2, 7, 1],
        [7, 2, 4, 5, 9],
        [8, 1, 8, 6, 8]]))

In [26]:
n1-n2

array([[-6, -5, -6, -3,  1],
       [ 4,  3,  4, -1,  5],
       [ 3, -6,  2,  1,  0],
       [-3,  3, -3,  4, -8],
       [-5,  0, -3,  3,  1]])

In [27]:
n6=np.random.randint(1,10,10)

In [28]:
n6

array([9, 7, 4, 8, 2, 6, 9, 6, 6, 7])

In [33]:
n7=np.random.randint(1,10,(4,4))
n7

array([[5, 8, 4, 8],
       [2, 8, 6, 3],
       [4, 8, 3, 8],
       [3, 5, 3, 2]])

In [38]:
print(n7[0])

[5 8 4 8]


In [37]:
print(n7[:,0])

[5 2 4 3]


In [39]:
print(n7[-1])

[3 5 3 2]


In [40]:
print(n7[:2,2:])

[[4 8]
 [6 3]]
